name: pip_services3_container
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: It provides an inversion-of-control component container to facilitate the development of composable services and applications.
homepage: https://github.com/pip-services3-dart/pip-services3-container-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.3 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"

dev_dependencies:
  test: '>=1.14.2 <2.0.0'